name: Deploy Services

on:
  push:
    branches: [main]
    paths:
      - 'crm/**'
      - 'web/**'
      - 'config/**'
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'
        required: true
        type: choice
        options:
          - crm
          - web
          - both
        default: both

env:
  AWS_REGION: eu-west-1
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        service: ${{ inputs.service == 'both' && fromJson('["crm", "web"]') || fromJson(format('["{0}"]', inputs.service)) }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy ${{ matrix.service }} service
      run: |
        chmod +x deploy/build.sh
        ./deploy/build.sh ${{ matrix.service }} ${{ env.ENVIRONMENT }}
    
    - name: Verify deployment
      run: |
        SERVICE_NAME=${{ matrix.service }}-service-${{ env.ENVIRONMENT }}
        CLUSTER_NAME=data-pipeline-cluster-${{ env.ENVIRONMENT }}
        
        SERVICE_STATUS=$(aws ecs describe-services \
          --cluster $CLUSTER_NAME \
          --services $SERVICE_NAME \
          --query 'services[0].{Running:runningCount,Desired:desiredCount,Status:status}')
        
        echo "Service Status: $SERVICE_STATUS"
