name: Destroy Environment

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string
      preserve_data:
        description: 'Preserve S3 data'
        required: false
        default: true
        type: boolean

env:
  AWS_REGION: eu-west-1
  ENVIRONMENT: dev

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ inputs.confirm }}" != "DESTROY" ]; then
          echo "❌ Destruction not confirmed"
          exit 1
        fi
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Destroy resources
      run: |
        chmod +x deploy/cleanup.sh
        ./deploy/cleanup.sh ${{ env.ENVIRONMENT }} ${{ inputs.preserve_data }}
