name: Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - create
          - update
        default: create

env:
  AWS_REGION: eu-west-1
  ENVIRONMENT: dev

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup infrastructure
      run: |
        chmod +x deploy/infra.sh
        ./deploy/infra.sh ${{ env.ENVIRONMENT }}
    
    - name: Output summary
      run: |
        echo "✅ Infrastructure setup completed for environment: ${{ env.ENVIRONMENT }}"
